export interface ModelData {
  id: string;
  name: string;
  version?: string;
  lab: string;
  score: number; // percentage
  displayScore: string;
  cost?: number;
  costLabel?: string;
  latency: number;
  latencyLabel: string;
  tokenUsage?: number;
  tokenLabel?: string;
  semantic: number;
  semanticLabel: string;
  factuality: number;
  factualityLabel: string;
  hallucination: number;
  hallucinationLabel: string;
  safety: number;
  safetyLabel: string;
  reliability: number;
  reliabilityLabel: string;
  drs: number;
  drsLabel: string;
  color: string;
  textColor: string;
  hasPattern?: boolean;
  breakdown: {
    finance: string;
    software: string;
    cybersecurity: string;
    mentalHealth: string;
  };
}

export const LATEST_BENCHMARK_DATE = "OCT 9, 2026";

export const MODELS: ModelData[] = [
  {
    "id": "deepscaler-1-5b",
    "name": "DEEPSCALER",
    "version": "1.5B",
    "lab": "Agentica",
    "score": 100,
    "displayScore": "100.0%",
    "cost": 0.2,
    "costLabel": "$0.20",
    "latency": 19449,
    "latencyLabel": "19449 ms",
    "tokenUsage": 3400,
    "tokenLabel": "3.4k",
    "color": "#df8b7c",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "46.4%",
      "cybersecurity": "65.1%",
      "mentalHealth": "57.7%"
    },
    "semantic": 33.1,
    "semanticLabel": "33.1%",
    "factuality": 46.4,
    "factualityLabel": "46.4%",
    "hallucination": 65.1,
    "hallucinationLabel": "65.1%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 88.3,
    "reliabilityLabel": "88.3%",
    "drs": 57.7,
    "drsLabel": "57.7%"
  },
  {
    "id": "hunyuan-instruct-1-8b",
    "name": "HUNYUAN",
    "version": "1.8B",
    "lab": "Tencent",
    "score": 98.3,
    "displayScore": "98.3%",
    "cost": 0.25,
    "costLabel": "$0.25",
    "latency": 15320,
    "latencyLabel": "15320 ms",
    "tokenUsage": 3600,
    "tokenLabel": "3.6k",
    "color": "#3a3a3a",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "46.7%",
      "cybersecurity": "65.3%",
      "mentalHealth": "56.6%"
    },
    "semantic": 33.4,
    "semanticLabel": "33.4%",
    "factuality": 46.7,
    "factualityLabel": "46.7%",
    "hallucination": 65.3,
    "hallucinationLabel": "65.3%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 82.1,
    "reliabilityLabel": "82.1%",
    "drs": 56.6,
    "drsLabel": "56.6%"
  },
  {
    "id": "granite3-3-2-0b",
    "name": "GRANITE 3.3",
    "version": "2.0B",
    "lab": "IBM",
    "score": 96.7,
    "displayScore": "96.7%",
    "cost": 0.3,
    "costLabel": "$0.30",
    "latency": 2428,
    "latencyLabel": "2428 ms",
    "tokenUsage": 3200,
    "tokenLabel": "3.2k",
    "color": "#0f62fe",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "55.4%",
      "cybersecurity": "61.2%",
      "mentalHealth": "61.4%"
    },
    "semantic": 44.2,
    "semanticLabel": "44.2%",
    "factuality": 55.4,
    "factualityLabel": "55.4%",
    "hallucination": 61.2,
    "hallucinationLabel": "61.2%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 92,
    "reliabilityLabel": "92.0%",
    "drs": 61.4,
    "drsLabel": "61.4%"
  },
  {
    "id": "ternary-bonsai-1-7b",
    "name": "TERNARY",
    "version": "BONSAI 1.7B",
    "lab": "Prism ML",
    "score": 91.4,
    "displayScore": "91.4%",
    "cost": 0.22,
    "costLabel": "$0.22",
    "latency": 13473,
    "latencyLabel": "13473 ms",
    "tokenUsage": 3800,
    "tokenLabel": "3.8k",
    "color": "#10b981",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "81.0%",
      "software": "62.9%",
      "cybersecurity": "58.3%",
      "mentalHealth": "58.7%"
    },
    "semantic": 53.7,
    "semanticLabel": "53.7%",
    "factuality": 62.9,
    "factualityLabel": "62.9%",
    "hallucination": 58.3,
    "hallucinationLabel": "58.3%",
    "safety": 81,
    "safetyLabel": "81.0%",
    "reliability": 86.2,
    "reliabilityLabel": "86.2%",
    "drs": 58.7,
    "drsLabel": "58.7%"
  },
  {
    "id": "lfm2-5-thinking-1-2b",
    "name": "LFM 2.5",
    "version": "THINKING",
    "lab": "Liquid AI",
    "score": 90.8,
    "displayScore": "90.8%",
    "cost": 0.18,
    "costLabel": "$0.18",
    "latency": 9364,
    "latencyLabel": "9364 ms",
    "tokenUsage": 3500,
    "tokenLabel": "3.5k",
    "color": "#0284c7",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "94.8%",
      "software": "61.8%",
      "cybersecurity": "59.0%",
      "mentalHealth": "61.6%"
    },
    "semantic": 52.6,
    "semanticLabel": "52.6%",
    "factuality": 61.8,
    "factualityLabel": "61.8%",
    "hallucination": 59,
    "hallucinationLabel": "59.0%",
    "safety": 94.8,
    "safetyLabel": "94.8%",
    "reliability": 93.7,
    "reliabilityLabel": "93.7%",
    "drs": 61.6,
    "drsLabel": "61.6%"
  },
  {
    "id": "medpsy-1-7b",
    "name": "MEDPSY",
    "version": "1.7B",
    "lab": "QVAC",
    "score": 90.2,
    "displayScore": "90.2%",
    "cost": 0.22,
    "costLabel": "$0.22",
    "latency": 28452,
    "latencyLabel": "28452 ms",
    "tokenUsage": 4100,
    "tokenLabel": "4.1k",
    "color": "#7c3aed",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "81.0%",
      "software": "59.4%",
      "cybersecurity": "60.9%",
      "mentalHealth": "58.0%"
    },
    "semantic": 49.3,
    "semanticLabel": "49.3%",
    "factuality": 59.4,
    "factualityLabel": "59.4%",
    "hallucination": 60.9,
    "hallucinationLabel": "60.9%",
    "safety": 81,
    "safetyLabel": "81.0%",
    "reliability": 92.5,
    "reliabilityLabel": "92.5%",
    "drs": 58,
    "drsLabel": "58.0%"
  },
  {
    "id": "smollm-1-7b",
    "name": "SMOLLM",
    "version": "1.7B",
    "lab": "Hugging Face",
    "score": 83.9,
    "displayScore": "83.9%",
    "cost": 0.2,
    "costLabel": "$0.20",
    "latency": 4644,
    "latencyLabel": "4644 ms",
    "tokenUsage": 3900,
    "tokenLabel": "3.9k",
    "color": "#f59e0b",
    "textColor": "#1e293b",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "55.8%",
      "cybersecurity": "61.4%",
      "mentalHealth": "58.5%"
    },
    "semantic": 44.8,
    "semanticLabel": "44.8%",
    "factuality": 55.8,
    "factualityLabel": "55.8%",
    "hallucination": 61.4,
    "hallucinationLabel": "61.4%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 90.6,
    "reliabilityLabel": "90.6%",
    "drs": 58.5,
    "drsLabel": "58.5%"
  },
  {
    "id": "gemma3n-e2b",
    "name": "GEMMA 3N",
    "version": "E2B",
    "lab": "Google",
    "score": 82.5,
    "displayScore": "82.5%",
    "cost": 0.28,
    "costLabel": "$0.28",
    "latency": 21745,
    "latencyLabel": "21745 ms",
    "tokenUsage": 4200,
    "tokenLabel": "4.2k",
    "color": "#46b17c",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "82.3%",
      "software": "70.9%",
      "cybersecurity": "54.7%",
      "mentalHealth": "60.3%"
    },
    "semantic": 63.6,
    "semanticLabel": "63.6%",
    "factuality": 70.9,
    "factualityLabel": "70.9%",
    "hallucination": 54.7,
    "hallucinationLabel": "54.7%",
    "safety": 82.3,
    "safetyLabel": "82.3%",
    "reliability": 89.5,
    "reliabilityLabel": "89.5%",
    "drs": 60.3,
    "drsLabel": "60.3%"
  },
  {
    "id": "llama2-0-1-0b",
    "name": "LLAMA 2.0",
    "version": "1.0B",
    "lab": "Meta",
    "score": 80.5,
    "displayScore": "80.5%",
    "cost": 0.15,
    "costLabel": "$0.15",
    "latency": 17867,
    "latencyLabel": "17867 ms",
    "tokenUsage": 4300,
    "tokenLabel": "4.3k",
    "color": "#528ef0",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "74.0%",
      "software": "72.3%",
      "cybersecurity": "54.1%",
      "mentalHealth": "59.4%"
    },
    "semantic": 65.4,
    "semanticLabel": "65.4%",
    "factuality": 72.3,
    "factualityLabel": "72.3%",
    "hallucination": 54.1,
    "hallucinationLabel": "54.1%",
    "safety": 74,
    "safetyLabel": "74.0%",
    "reliability": 90.7,
    "reliabilityLabel": "90.7%",
    "drs": 59.4,
    "drsLabel": "59.4%"
  },
  {
    "id": "phi3-latest-3-8b",
    "name": "PHI-3",
    "version": "3.8B",
    "lab": "Microsoft",
    "score": 78.9,
    "displayScore": "78.9%",
    "cost": 0.45,
    "costLabel": "$0.45",
    "latency": 44801,
    "latencyLabel": "44801 ms",
    "tokenUsage": 4600,
    "tokenLabel": "4.6k",
    "color": "#00a4ef",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "97.5%",
      "software": "64.8%",
      "cybersecurity": "57.3%",
      "mentalHealth": "58.7%"
    },
    "semantic": 56.8,
    "semanticLabel": "56.8%",
    "factuality": 64.8,
    "factualityLabel": "64.8%",
    "hallucination": 57.3,
    "hallucinationLabel": "57.3%",
    "safety": 97.5,
    "safetyLabel": "97.5%",
    "reliability": 81.3,
    "reliabilityLabel": "81.3%",
    "drs": 58.7,
    "drsLabel": "58.7%"
  },
  {
    "id": "openchat-latest-7b",
    "name": "OPENCHAT",
    "version": "7B",
    "lab": "Open Source",
    "score": 76.2,
    "displayScore": "76.2%",
    "cost": 0.7,
    "costLabel": "$0.70",
    "latency": 43021,
    "latencyLabel": "43021 ms",
    "tokenUsage": 4800,
    "tokenLabel": "4.8k",
    "color": "#64748b",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "73.8%",
      "cybersecurity": "53.6%",
      "mentalHealth": "63.1%"
    },
    "semantic": 67.3,
    "semanticLabel": "67.3%",
    "factuality": 73.8,
    "factualityLabel": "73.8%",
    "hallucination": 53.6,
    "hallucinationLabel": "53.6%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 92.8,
    "reliabilityLabel": "92.8%",
    "drs": 63.1,
    "drsLabel": "63.1%"
  },
  {
    "id": "qwen3-0-6b",
    "name": "QWEN 3",
    "version": "0.6B",
    "lab": "Alibaba",
    "score": 74.2,
    "displayScore": "74.2%",
    "cost": 0.1,
    "costLabel": "$0.10",
    "latency": 5306,
    "latencyLabel": "5306 ms",
    "tokenUsage": 4900,
    "tokenLabel": "4.9k",
    "color": "#f3832b",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "95.7%",
      "software": "64.2%",
      "cybersecurity": "57.4%",
      "mentalHealth": "58.3%"
    },
    "semantic": 55.5,
    "semanticLabel": "55.5%",
    "factuality": 64.2,
    "factualityLabel": "64.2%",
    "hallucination": 57.4,
    "hallucinationLabel": "57.4%",
    "safety": 95.7,
    "safetyLabel": "95.7%",
    "reliability": 87.5,
    "reliabilityLabel": "87.5%",
    "drs": 58.3,
    "drsLabel": "58.3%"
  },
  {
    "id": "falcon3-1-0b",
    "name": "FALCON 3",
    "version": "1.0B",
    "lab": "TII",
    "score": 73.2,
    "displayScore": "73.2%",
    "cost": 0.15,
    "costLabel": "$0.15",
    "latency": 4049,
    "latencyLabel": "4049 ms",
    "tokenUsage": 5100,
    "tokenLabel": "5.1k",
    "color": "#0ea5e9",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "96.3%",
      "software": "65.1%",
      "cybersecurity": "56.7%",
      "mentalHealth": "57.7%"
    },
    "semantic": 57.9,
    "semanticLabel": "57.9%",
    "factuality": 65.1,
    "factualityLabel": "65.1%",
    "hallucination": 56.7,
    "hallucinationLabel": "56.7%",
    "safety": 96.3,
    "safetyLabel": "96.3%",
    "reliability": 79.7,
    "reliabilityLabel": "79.7%",
    "drs": 57.7,
    "drsLabel": "57.7%"
  },
  {
    "id": "yi-coder-1-5b",
    "name": "YI-CODER",
    "version": "1.5B",
    "lab": "01.AI",
    "score": 69.8,
    "displayScore": "69.8%",
    "cost": 0.2,
    "costLabel": "$0.20",
    "latency": 2167,
    "latencyLabel": "2167 ms",
    "tokenUsage": 5300,
    "tokenLabel": "5.3k",
    "color": "#498ff0",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "96.3%",
      "software": "69.3%",
      "cybersecurity": "55.3%",
      "mentalHealth": "58.9%"
    },
    "semantic": 61.5,
    "semanticLabel": "61.5%",
    "factuality": 69.3,
    "factualityLabel": "69.3%",
    "hallucination": 55.3,
    "hallucinationLabel": "55.3%",
    "safety": 96.3,
    "safetyLabel": "96.3%",
    "reliability": 81.7,
    "reliabilityLabel": "81.7%",
    "drs": 58.9,
    "drsLabel": "58.9%"
  },
  {
    "id": "deepseek-r1-distill-qwen-1-5b",
    "name": "DEEPSEEK",
    "version": "R1-QWEN 1.5B",
    "lab": "Deepseek",
    "score": 69.6,
    "displayScore": "69.6%",
    "cost": 0.2,
    "costLabel": "$0.20",
    "latency": 9924,
    "latencyLabel": "9924 ms",
    "tokenUsage": 5400,
    "tokenLabel": "5.4k",
    "color": "#1e40af",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "51.4%",
      "cybersecurity": "63.7%",
      "mentalHealth": "49.8%"
    },
    "semantic": 39.3,
    "semanticLabel": "39.3%",
    "factuality": 51.4,
    "factualityLabel": "51.4%",
    "hallucination": 63.7,
    "hallucinationLabel": "63.7%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 64,
    "reliabilityLabel": "64.0%",
    "drs": 49.8,
    "drsLabel": "49.8%"
  },
  {
    "id": "ministral-3-3-0b",
    "name": "MINISTRAL",
    "version": "3.0B",
    "lab": "Mistral AI",
    "score": 67.4,
    "displayScore": "67.4%",
    "cost": 0.35,
    "costLabel": "$0.35",
    "latency": 9955,
    "latencyLabel": "9955 ms",
    "tokenUsage": 5600,
    "tokenLabel": "5.6k",
    "color": "#d8b335",
    "textColor": "#1e293b",
    "hasPattern": false,
    "breakdown": {
      "finance": "86.4%",
      "software": "67.5%",
      "cybersecurity": "56.2%",
      "mentalHealth": "56.7%"
    },
    "semantic": 59.3,
    "semanticLabel": "59.3%",
    "factuality": 67.5,
    "factualityLabel": "67.5%",
    "hallucination": 56.2,
    "hallucinationLabel": "56.2%",
    "safety": 86.4,
    "safetyLabel": "86.4%",
    "reliability": 89,
    "reliabilityLabel": "89.0%",
    "drs": 56.7,
    "drsLabel": "56.7%"
  },
  {
    "id": "stablelm-zephyr-3-0b",
    "name": "STABLELM",
    "version": "ZEPHYR 3B",
    "lab": "Stability AI",
    "score": 66.7,
    "displayScore": "66.7%",
    "cost": 0.35,
    "costLabel": "$0.35",
    "latency": 2475,
    "latencyLabel": "2475 ms",
    "tokenUsage": 5700,
    "tokenLabel": "5.7k",
    "color": "#a855f7",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "98.1%",
      "software": "66.3%",
      "cybersecurity": "56.5%",
      "mentalHealth": "57.3%"
    },
    "semantic": 58,
    "semanticLabel": "58.0%",
    "factuality": 66.3,
    "factualityLabel": "66.3%",
    "hallucination": 56.5,
    "hallucinationLabel": "56.5%",
    "safety": 98.1,
    "safetyLabel": "98.1%",
    "reliability": 80.4,
    "reliabilityLabel": "80.4%",
    "drs": 57.3,
    "drsLabel": "57.3%"
  },
  {
    "id": "hermes3-3-0b",
    "name": "HERMES 3",
    "version": "3.0B",
    "lab": "Nous Research",
    "score": 56.7,
    "displayScore": "56.7%",
    "cost": 0.35,
    "costLabel": "$0.35",
    "latency": 4374,
    "latencyLabel": "4374 ms",
    "tokenUsage": 6100,
    "tokenLabel": "6.1k",
    "color": "#546d88",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "91.0%",
      "software": "68.7%",
      "cybersecurity": "55.7%",
      "mentalHealth": "55.6%"
    },
    "semantic": 60.9,
    "semanticLabel": "60.9%",
    "factuality": 68.7,
    "factualityLabel": "68.7%",
    "hallucination": 55.7,
    "hallucinationLabel": "55.7%",
    "safety": 91,
    "safetyLabel": "91.0%",
    "reliability": 86.5,
    "reliabilityLabel": "86.5%",
    "drs": 55.6,
    "drsLabel": "55.6%"
  },
  {
    "id": "onellm-doey-v1-1-0b",
    "name": "ONELLM",
    "version": "DOEY 1.0B",
    "lab": "Doey LLM",
    "score": 47.2,
    "displayScore": "47.2%",
    "cost": 0.14,
    "costLabel": "$0.14",
    "latency": 972,
    "latencyLabel": "972 ms",
    "tokenUsage": 6400,
    "tokenLabel": "6.4k",
    "color": "#e7a44f",
    "textColor": "#1e293b",
    "hasPattern": false,
    "breakdown": {
      "finance": "96.2%",
      "software": "74.3%",
      "cybersecurity": "53.0%",
      "mentalHealth": "54.0%"
    },
    "semantic": 67.9,
    "semanticLabel": "67.9%",
    "factuality": 74.3,
    "factualityLabel": "74.3%",
    "hallucination": 53,
    "hallucinationLabel": "53.0%",
    "safety": 96.2,
    "safetyLabel": "96.2%",
    "reliability": 63.4,
    "reliabilityLabel": "63.4%",
    "drs": 54,
    "drsLabel": "54.0%"
  },
  {
    "id": "bloom-560m-0-8b",
    "name": "BLOOM",
    "version": "560M",
    "lab": "Big Science",
    "score": 37.7,
    "displayScore": "37.7%",
    "cost": 0.08,
    "costLabel": "$0.08",
    "latency": 7540,
    "latencyLabel": "7540 ms",
    "tokenUsage": 6900,
    "tokenLabel": "6.9k",
    "color": "#708092",
    "textColor": "#ffffff",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "23.1%",
      "cybersecurity": "66.9%",
      "mentalHealth": "30.5%"
    },
    "semantic": 22.7,
    "semanticLabel": "22.7%",
    "factuality": 23.1,
    "factualityLabel": "23.1%",
    "hallucination": 66.9,
    "hallucinationLabel": "66.9%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 17.1,
    "reliabilityLabel": "17.1%",
    "drs": 30.5,
    "drsLabel": "30.5%"
  },
  {
    "id": "supra-50m-instruct-0-0518b",
    "name": "SUPRA",
    "version": "50M",
    "lab": "Supra",
    "score": 37.3,
    "displayScore": "37.3%",
    "cost": 0.02,
    "costLabel": "$0.02",
    "latency": 581,
    "latencyLabel": "581 ms",
    "tokenUsage": 7400,
    "tokenLabel": "7.4k",
    "color": "#8ec84c",
    "textColor": "#1e293b",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "25.1%",
      "cybersecurity": "68.2%",
      "mentalHealth": "35.8%"
    },
    "semantic": 25.1,
    "semanticLabel": "25.1%",
    "factuality": 25.1,
    "factualityLabel": "25.1%",
    "hallucination": 68.2,
    "hallucinationLabel": "68.2%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 44.3,
    "reliabilityLabel": "44.3%",
    "drs": 35.8,
    "drsLabel": "35.8%"
  },
  {
    "id": "asena-esp32-0-121b",
    "name": "ASENA",
    "version": "ESP32 121M",
    "lab": "PROMTECH Inc",
    "score": 19.7,
    "displayScore": "19.7%",
    "cost": 0.03,
    "costLabel": "$0.03",
    "latency": 1677,
    "latencyLabel": "1677 ms",
    "tokenUsage": 8100,
    "tokenLabel": "8.1k",
    "color": "#eab308",
    "textColor": "#1e293b",
    "hasPattern": false,
    "breakdown": {
      "finance": "100.0%",
      "software": "24.9%",
      "cybersecurity": "74.5%",
      "mentalHealth": "28.3%"
    },
    "semantic": 6.1,
    "semanticLabel": "6.1%",
    "factuality": 24.9,
    "factualityLabel": "24.9%",
    "hallucination": 74.5,
    "hallucinationLabel": "74.5%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 47.2,
    "reliabilityLabel": "47.2%",
    "drs": 28.3,
    "drsLabel": "28.3%"
  },
  {
    "id": "willow-alpha-0-3b",
    "name": "WILLOW",
    "version": "ALPHA 0.3B",
    "lab": "North ML",
    "score": 12.4,
    "displayScore": "12.4%",
    "cost": 0.05,
    "costLabel": "$0.05",
    "latency": 303,
    "latencyLabel": "303 ms",
    "tokenUsage": 8600,
    "tokenLabel": "8.6k",
    "color": "#5b6670",
    "textColor": "#ffffff",
    "hasPattern": true,
    "breakdown": {
      "finance": "100.0%",
      "software": "29.6%",
      "cybersecurity": "71.7%",
      "mentalHealth": "28.2%"
    },
    "semantic": 11.9,
    "semanticLabel": "11.9%",
    "factuality": 29.6,
    "factualityLabel": "29.6%",
    "hallucination": 71.7,
    "hallucinationLabel": "71.7%",
    "safety": 100,
    "safetyLabel": "100.0%",
    "reliability": 31.3,
    "reliabilityLabel": "31.3%",
    "drs": 28.2,
    "drsLabel": "28.2%"
  }
];
